### ISSUE TITLE
add a github release with binaries

### ISSUE THREAD

**Issue by Gregy** [munjeni/newflasher#4]
Hi,
thanks so much for newflasher! I was able to get VoLTE on my phone because of it (the default firmware has it disabled...)

I spent a lot of time getting newflasher to build (I succeeded in the end). Could you maybe create a github release and upload the binaries too? I wasn't able to download the binaries from XDA because it always gave me 410 (probably some problem on their side).

Thank you

**Comment by munjeni** [comment]
Hi! I just tried download link and it worked! Try this link https://forum.xda-developers.com/attachment.php?attachmentid=4490283&d=1525166448

**Comment by Gregy** [comment]
Yep, working today. Probably some kind of temporary error. Thank you.
