### ISSUE TITLE
Hi, I have some problem when I flash my phone ，could you help me？

### ISSUE THREAD

**Issue by frozenfortress** [munjeni/newflasher#43]
Hi, i have some problem when i flash my phone ，could you help me...
I want to flash my SO-05K to 52.1.A.0.618  version(which can temp root ), but i couldn‘t find this version of firmware for my device。
There is another firmware for H8314 ，so i want to flash it to my device ，but newflasher show "Error, didn't got signature OKAY reply! Got reply: FAILFailed to verify cms",i tried flashtool,tried replace .000 file but filed.....
i read the newflasher.c and find the code at line 1722 , i think  i can bypass the signature detection if i delete line 1723 and use gcc rebuild the newflasher.exe , but i didn‘t have the *.h file like expat.h to rebuild , could you give me some advice or some help？thank you very very much！！sorry for my bad english，i have almost twelve years live without english……thank you very very much again！！

**Comment by munjeni** [comment]
Take a look into make file! One more thing, don't waste your time, you can't bypass signature verification, even you can't make your own sin file it all signed with sony private key!

**Comment by frozenfortress** [comment]
Thank you for your reply！I will try something else
