### ISSUE TITLE
'libusb.h' file not found (on M1 Macs)

### ISSUE THREAD

**Issue by sagz** [munjeni/newflasher#45]
<img width="837" alt="image" src="https://user-images.githubusercontent.com/964843/145932147-a91529b1-4139-4eb0-aa20-f7c370eac1c7.png">

Any idea what can help? thanks!

**Comment by munjeni** [comment]
Your include path seems not contain libusb.h or your include path is wrong : /usr/local/Cellar/libusb/1.0.23/include/libusb-1.0

chect it and try find location of the libusb header files!
