### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by rhamadhany** [munjeni/newflasher#46]
How to fix this, When I use version 52 it will be like this 

![Screenshot_20211223-014912_Termux](https://user-images.githubusercontent.com/77799700/147135574-779c3d7d-c774-4d5a-9425-e0b8ab66fa17.png)

Written protocol error or writtenIt says protocol error or sometimes connection timeout, but when using version 30 it will work like this 

![Screenshot_20211223-015435_Termux](https://user-images.githubusercontent.com/77799700/147135660-2889ab24-2a46-4181-8396-69f247621e1a.png)

I'm running linux on android, and maybe it's a problem with my usb port but why on version 30 it works. And I once ran v52 on the pc it ran smoothly, But my pc is broken so I run linux on android..

**Comment by munjeni** [comment]
Hello, you running linux on android, how?

**Comment by rhamadhany** [comment]
> Hello, you running linux on android, how?

I run it with chroot, to be precise with the nethunter application

**Comment by rhamadhany** [comment]
![Screenshot_20211223-025500](https://user-images.githubusercontent.com/77799700/147141553-3794accf-8de4-4bdb-9176-16409493fb7c.png)

Like this

**Comment by munjeni** [comment]
Well this is not corectly yet running on your android, you can see red lines, the most of things is not mounted yet! This is not a newflasher isue and I going to close this isue, further questions please ask in kali chroot support forum ok

**Comment by rhamadhany** [comment]
It's because I didn't run it

**Comment by rhamadhany** [comment]
![Screenshot_20211223-030600](https://user-images.githubusercontent.com/77799700/147142735-81953bb4-b879-4c3d-8613-dcea3731bfe6.png)

You mean like this?

**Comment by munjeni** [comment]
Try disable selinux first than try again, the important thing is those red lines you getting must not exist!

**Comment by munjeni** [comment]
setenforce 0

**Comment by munjeni** [comment]
can you post dmesg log?

**Comment by rhamadhany** [comment]
> setenforce 0

My Enforce is already running on permissive

**Comment by munjeni** [comment]
can you post dmesg log? Paste it here -> www.pastebin.com

**Comment by munjeni** [comment]
Did you tried android native binary from here? -> https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/

**Comment by rhamadhany** [comment]
> can you post dmesg log? Paste it here -> [www.pastebin.com](http://www.pastebin.com)

Sorry I can't copy it, on the site earlier because the size is more than 512 kb. So I uploaded it here

**Comment by rhamadhany** [comment]
> Did you tried android native binary from here not trought kali but from android directly? -> https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/

I've tried using the newflasher on xda and also using the one from github but it's the same for version 52. Which confuses me why it can work in version 30

**Comment by munjeni** [comment]
Please try version 30 right now, maybe it worked month ago but now not because of something I don't know

**Comment by munjeni** [comment]
You have runnig usb hub? This is what I have found in your dmesg:

[30844.160851] mdss_dp_probe: Error usbpd setup!
[30844.161804] hub 2-0:1.0: USB hub found
[30844.162055] hub 2-0:1.0: 1 port detected
[30844.163909] mdss_dp_usbpd_setup: get_usbpd phandle failed (-19)
[30844.163926] mdss_dp_probe: Error usbpd setup!

**Comment by munjeni** [comment]
There is apsolutly no diferencie in usb protocol on android and linux blob between version 30 and version 52, the most changes on usb protocol is done on windows blob only, so it might work the same as version 30 in relation to usb protocol. You have other problem which I don't know which one

**Comment by munjeni** [comment]
Also I can see in your dmesg that you have using usb hub, maybe hub isue?

**Comment by rhamadhany** [comment]
It's okay, because I can still use version 30

**Comment by rhamadhany** [comment]
I'm not using a usb hub, just otg

**Comment by rhamadhany** [comment]
![Screenshot_20211223-043056_Termux](https://user-images.githubusercontent.com/77799700/147151780-08624148-0e02-415c-863c-f54923e74ec4.png)

**Comment by munjeni** [comment]
Sorry I don't see any changes between v30 and v52 that might cause "protocol error", protocol is not changed between versions, only for windows and darwin build, android and linux is unchanged

**Comment by munjeni** [comment]
CAn you post whole newlfasher log from the start to the end from v52 ?

**Comment by rhamadhany** [comment]
![Screenshot_20211223-045551_Termux](https://user-images.githubusercontent.com/77799700/147154092-b86ea2ff-886a-4fab-b2d5-09e17d4e448c.png)

Now stuck in here

> Only maybe this variable: getvar:slot-count cause problem? Try delete lines from 3829 to 3879 https://github.com/munjeni/newflasher/blob/master/newflasher.c#L3829 and recompile newflasher

**Comment by munjeni** [comment]
Realy stuck?

**Comment by munjeni** [comment]
Try strace or something to see whats going on. Maybe better idea to debug it with gdb, I realy have idea whats going on with it, last time when I tried newflasher on android it was 3 years ago and it worked

**Comment by rhamadhany** [comment]
Ok I will also find out what went wrong

**Comment by rhamadhany** [comment]
![Screenshot_20211224-053211_Termux](https://user-images.githubusercontent.com/77799700/147320078-8d4ef619-b42b-4950-9c1f-a937367b7424.png)

Always stuck here on version 52

**Comment by munjeni** [comment]
Sorry I can do nothing right now until I get another device and test on my own, realy have no idea right now. Can you compile native android binary and test regulary out of chroot linux?

**Comment by munjeni** [comment]
Can you do? https://cs.baylor.edu/~donahoo/tools/gdb/tutorial.html

**Comment by rhamadhany** [comment]
![Screenshot_20211224-215019_Termux](https://user-images.githubusercontent.com/77799700/147357131-efe879f9-d1df-4886-b38a-128e82966399.png)
 

I don't know the command on gdb

**Comment by munjeni** [comment]
If you can't don't ask please, I don't have free time for this, when I get free time I will try debug it

**Comment by munjeni** [comment]
This might help? http://www.cs.toronto.edu/~krueger/csc209h/tut/gdb_tutorial.html

**Comment by rhamadhany** [comment]
I tried all versions of newflasher and it ended up in v38, and got the same problem in v39. but... after a few days i tried to take v52 on xda, and tried it but still the same, but... when i did it only with termux without my linux distro, it did flash.. so i guess the problem happened when i upgraded to my linux distro so i'm sorry its a problem with my distro not your tool :)
