### ISSUE TITLE
Has chosen to skip userdata but userdata.sin is still flashed

### ISSUE THREAD

**Issue by zyf0330** [munjeni/newflasher#47]
I choose skip userdata, and rename userdata sin to prefix `_`, but userdata is still flashed and my all data is lost.
Ridiculous! I check code logic and don't know why update.xml is still checked and userdata is flashed, after I has chosen skip userdata.

**Comment by zyf0330** [comment]
So I think the skip prompt is not necessary, and it makes people confused
now because program doesn't respect user choice.

**Comment by munjeni** [comment]
Program fully working ONLY when nothing is modified, deleted, renamed inside firmware folder downloaded trought xperifirm
