### ISSUE TITLE
Xperia 1 III(XQ-BC72) baseband lost

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [munjeni/newflasher#48]
I has flash 61.1.A.2.211(Cust SEA, Android 12) into system ver  61.0.A.23.20(Cust CN, Android 11) when active slot is b
when it end and phone reboot, it got into boot loop
after 3 times reboot, I got "device isn't trusted and no boot" alarm
when I force power off and connect it in flash mode, newflasher show baseband version is the old one
so I try use tool send "set_active:a" cmd to device, then newflasher show current slot is a, then I flash it again
after this time, it can boot into system normally and show system is Android 12
but when I plug my phone card in, there shows no signal
then I open service menu, found IMEI and Softwear Verision become UNKNOWN
Now it seem that cellular function totally break down
Did baseband won't flash in flash process or missed file?

**Comment by munjeni** [comment]
Hello, this is not a nwflasher related isue but inproper firmware model for your model, please login to xda forum, there is a lot of posts relatd to your problem, this have nothing to do with newflasher.

**Comment by agusdallalba** [comment]
I had this problem when flashing to slot B.

The phone was originally in slot A with the corrupted error. Re-flashing slot A usually fixes this problem but I wanted to try and fix it permanently.

I flashed everything (except userdata) with newflasher (on slot A) and then used set_active:b and ran newflasher again on slot B as well.

The phone got into a bootloop on the xperia logo, so I switched back to slot A with set_active:a.

Rebooted to Android and the modem wasn't working.

Ran newflasher again (on slot A) and this fixed the modem.

In every case I was using the exact same firmware files: `XQ-BQ52_Customized EEA_61.2.A.0.472A`. There's probably something wrong with newflasher.

**Comment by munjeni** [comment]
You must understand that each firmware contain things which flashes tthings to booth slots, for example if you are curently on one slot some files is flashed to another slot and in that case if you change slot after flashing you must understand that things which is previously flashed to another thing will not work, so do not change slot after flashing and things will work! I recomend always to keep slot A and not slot B. Hope this help.

**Comment by agusdallalba** [comment]
I understand, but please document somewhere that newflasher doesn't work correctly with the b slot, I spent days dealing with this problem.

If the issue had been left open I could have spend the time fixing it and sending a PR.

Kind regards.

**Comment by munjeni** [comment]
That is not isue by newflasher.
