### ISSUE TITLE
No usb device with vid:0x0fce pid:0xb00b

### ISSUE THREAD

**Issue by biopsin** [munjeni/newflasher#5]
Hi there,
I succsessfully downgraded using newflasher couple of days ago, then I accedentaly updated firmware (big fingers), so I tried downgrading again, but now I get
...
Determining available free space:

  Available space to caller    = 173219 MB
  Total space on current drive = 300325 MB
  Free space on drive          = 173235 MB
cannot open /dev/bus/usb/004/001 for writing
cannot open /dev/bus/usb/003/004 for writing
cannot open /dev/bus/usb/003/003 for writing
cannot open /dev/bus/usb/003/002 for writing
cannot open /dev/bus/usb/003/001 for writing
cannot open /dev/bus/usb/002/002 for writing
cannot open /dev/bus/usb/002/001 for writing
cannot open /dev/bus/usb/001/002 for writing
cannot open /dev/bus/usb/001/001 for writing

No usb device with vid:0x0fce pid:0xb00b !
...
$ lsusb 
Bus 003 Device 009: ID 0fce:0dde Sony Ericsson Mobile Communications AB Xperia Mini Pro Bootloader

Adb is working and I have android-tools installed and nothing has change on my system in between these days, no system updates.
I have browsed XDA forum and there is no information other then install drivers..
but I just flashed resently on the same system, any Ideas?
(Linux x64 + android-tools-9.0.0.r30)

**Comment by munjeni** [comment]
Hi, thats unrelated to newflasher. Your device is currently in fastboot mode, you need to enter your device info flash mode, to do that press and hold volumedown+power buttons!

**Comment by VGerris** [comment]
hi, that does not work on my XZ, I get the exact same error, it shows a green light, not blue.

**Comment by munjeni** [comment]
Just to edit post above, fastboot mode is while holding volumeup & at the same time connect usb cable while holding volume down. Flash mode is when holding volumedown & at the same time connect usb cable while holding volume down.

**Comment by VGerris** [comment]
yeah, and that gives me this error :). I gave up on the device, I was able
to flash t with flashtool but it keeps bootlooping..

**Comment by munjeni** [comment]
Thats not newflasher isue since you have vid 0x0fce and pid 0x0dde:

Bus 003 Device 009: ID 0fce:0dde Sony Ericsson Mobile Communications AB Xperia Mini Pro Bootloader

indication for fastboot mode which mean your device when you press volume down and connect usb cable didn't enter into flash mode, instead it enter into fastboot mode.

**Comment by VGerris** [comment]
Hi,

It says service mode somewhere in another tool.
Fastboot mode works too and shows another id.
It just doesn't go to this flash mode.

Cheers

**Comment by munjeni** [comment]
Which vid and pid you get?

**Comment by VGerris** [comment]
Hi,

This is the relevant line from lsusb output:
Bus 001 Device 046: ID 0fce:adde Sony Ericsson Mobile Communications AB C2005 (Xperia M dual) in service mode
in fastboot mode:
Bus 001 Device 047: ID 0fce:0dde Sony Ericsson Mobile Communications AB Xperia Mini Pro Bootloader

**Comment by munjeni** [comment]
Newflasher can't be used on xperia M. Pid 0xadde is old s1 protocol used in xperia go for example, you should try xflasher https://forum.xda-developers.com/crossdevice-dev/sony/dev-xflasher-command-line-flasher-t2986634 , do in mind it might brick your device, I didn't remember which device have problem with xflasher, mediatek probably, search xda before you use xflasher!

**Comment by VGerris** [comment]
hi,

Thanks, it's an Xperia XZ, maybe 2016. I didn't know it was incompatible, thanks.
And thanks for your work :)!

greetings
Vincent

**Comment by bennypr0fane** [comment]
I have the same issue:
`cannot open /dev/bus/usb/004/002 for writing
cannot open /dev/bus/usb/004/001 for writing
cannot open /dev/bus/usb/003/001 for writing
cannot open /dev/bus/usb/002/001 for writing
cannot open /dev/bus/usb/001/004 for writing
cannot open /dev/bus/usb/001/003 for writing
cannot open /dev/bus/usb/001/002 for writing
cannot open /dev/bus/usb/001/001 for writing

No usb device with vid:0x0fce pid:0xb00b !`
I'm trying to flash an Xperia X, but I get the same line when I do lsusb with the device in flash mode (volume down, green light!):
`Bus 001 Device 005: ID 0fce:adde Sony Ericsson Mobile Communications AB C2005 (Xperia M dual) in service mode`

**Comment by munjeni** [comment]
I'm allready explined here, just read it. Not newflasher isue!
