### ISSUE TITLE
libusb problems on M1 mac

### ISSUE THREAD

**Issue by A2Sumie** [munjeni/newflasher#51]
dumping trim area or flashing with pre-compiled build gives the following error
`bulk transfer (in): LIBUSB_ERROR_OVERFLOW`

self-building gives error, modded makefiles `CFLAGS+= -I/opt/homebrew/Cellar/libusb/1.0.26/include/libusb-1.0` according to #45 

```
ld: library not found for -lusb-1.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [newflasher] Error 1
```

**Comment by munjeni** [comment]
You must provide path to the library too! For example

-L /opt/homebrew/Cellar/libusb/1.0.26/lib

depending of the real path to the libusb! If the name of the l;ibusb is not libusb-1.0.so or something else for example libusbname.so you must add one more aruments e.g.

-llusb-1.0

or

-llusbname
 
Depend of the real name of the libusb! So what you need to modify is probably:

ifeq ($(OS),Darwin)
CFLAGS+= -I /opt/homebrew/Cellar/libusb/1.0.26/include -L /opt/homebrew/Cellar/libusb/1.0.26/lib
LIBS+=-lusb-1.0
endif

Hope this help.

**Comment by ICHx** [comment]
I followed your instruction, instead, this worked for me

```
CFLAGS?=-Wall -g -O2
ifeq ($(OS),Darwin)
CFLAGS+= -L/opt/homebrew/Cellar/libusb/1.0.29/lib -I/opt/homebrew/Cellar/libusb/1.0.29/include/libusb-1.0/
# CFLAGS+= -I/usr/local/include/libusb-1.0
LIBS+=-lusb-1.0
endif
```

**Comment by ICHx** [comment]
As libusb.h wasn't directly under `/opt/homebrew/Cellar/libusb/1.0.26/include`
