### ISSUE TITLE
pre-compiled arm builds does not flash on Raspberry Pi 4

### ISSUE THREAD

**Issue by A2Sumie** [munjeni/newflasher#52]
Raspberry Pi 400 actually, running CentOS 7
tadump can be created successfully on the same machine, and there is data in the dumps.
```
Optional step! Type 'y' and press ENTER if you want dump trim area, or type 'n' and press ENTER to skip.
Do in mind this doesn't dump drm key since sake authentifiction is need for that! But it is recommend to have dump in case hard brick!
y
Dumping trimarea partition 1.
Created ouput folder tadump.
./tadump/tadump_1.ta created.
Dumping trimarea partition 2.
Dumping trim area to tadump folder.
./tadump/tadump_2.ta created.
Sent command: continue.

Done.
Closing device.
```
however, when trying to flash, newflasher gives the following error after a long freeze.
```
Optional step! Type 'y' and press ENTER if you want dump trim area, or type 'n' and press ENTER to skip.
Do in mind this doesn't dump drm key since sake authentifiction is need for that! But it is recommend to have dump in case hard brick!
n
 - (ep_out size=17)ERROR: n = -1, errno = 110 (Connection timed out)
 - Error writing command getvar:slot-count, ignore this error!
 - (ep_out size=14)ERROR: n = -1, errno = 110 (Connection timed out)
 - Error writing command getvar:Battery!
 - (ep_out size=4)ERROR: n = -1, errno = 110 (Connection timed out)
 - Error writing command Sync!
Closing device.
```

**Comment by munjeni** [comment]
You must disconnect usb and repeat procedure to enter into flash mode instead of imediatelly after dumping trim area trying to flash since command "continue" is allready sent so device is no more in flash mode!

**Comment by A2Sumie** [comment]
> You must disconnect usb and repeat procedure to enter into flash mode instead of imediatelly after dumping trim area trying to flash since command "continue" is allready sent so device is no more in flash mode!

I know that. I mean it's not flashing and giving the errors in flash mode , of course on an fresh connection. 
The phone is an XQ-AS72.

**Comment by munjeni** [comment]
Probably wrong. Can you show me log of the command lsusb ?
