### ISSUE TITLE
Xperia 1 III (XQ-BC72) flash failed

### ISSUE THREAD

**Issue by weijen6** [munjeni/newflasher#57]
D:\mobiletools\Root\SONY\XQ-BC72_61.0.A.23.20_Customized_TW>newflasher
--------------------------------------------------------
            newflasher v55 by Munjeni @ 2017/2020
--------------------------------------------------------

Determining available free space by GetDiskFreeSpaceEx:

  Available space to caller    = 1192879 MB
  Total space on current drive = 11444223 MB
  Free space on drive          = 1192879 MB

Optional step! Type 'y' and press ENTER if you need GordonGate flash driver, or type 'n' to skip.
This creates GordonGate driver installer in the same dir with newflasher!
n
Device path: \\?\usb#vid_0fce&pid_b00b#5&15c311e1&0&10#{a5dcbf10-6530-11d2-901f-00c04fb951ed}
Class Description: SOMC Flash Device
Device Instance Id: USB\VID_0FCE&PID_B00B\5&15C311E1&0&10

update.xml not exist in current folder!

Reboot mode at the end of flashing:
  type 'a' for reboot to android, type 'f' for reboot to fastboot, type 's' for reboot to same mode, type 'p' for poweroff, and press ENTER.
a

Optional step! Type 'y' and press ENTER if you want dump trim area, or type 'n' and press ENTER to skip.
Do in mind this doesn't dump drm key since sake authentifiction is need for that! But it is recommend to have dump in case hard brick!
n
Product: XQ-BC72
Version: 0.4
Bootloader version: 1322-1669_X_Boot_SM8350_LA2.0.1_T_205
Baseband version: 61.2.A.0.382
Serialno: QV7800XA8G
Secure: yes
Loader version: 1322-1669_X_Boot_SM8350_LA2.0.1_T_205
Phone ID: 0000:35292034044036,0000:35292034044037
Device ID: BB8788E0
Platform ID: 301350E1
Max download size: 805306368
Sector size: 4096
Rooting status: ROOTABLE
Ufs info: SKhynix,HN8T15BZGKX016,A002
Emmc info: FAILEmmc-info not supported
Default security: ON
Keystore counter: 2
Security state: 3ZSdgbZm7KCDQGLaJXvBJAFt57+Ggguoee3iMp9Gj+s=
Sake root: 032F03E14777E1B8A88520664B7B
S1 root:
Root key hash: DE899A8AE73A3BB3062F1597B3316A930095EEC7CE8BD9641DE7850E034211E10B8D032F03E14777E1B8A88520664B7B
Slot count: 2
Current slot: a
Battery level: 15

Device is put now in flash mode.

Repartitioning...
partition_delivery.xml not exist in partition folder or no partition folder.

Processing partition-image-LUN0_124936192_X-FLASH-ALL-4BA8.sin
 - Extracting from partition-image-LUN0_124936192_X-FLASH-ALL-4BA8.sin
 - Extracting signature partitionimage_0.cms
 - Uploading signature D:\mobiletools\Root\SONY\XQ-BC72_61.0.A.23.20_Customized_TW\partition\partitionimage_0.cms
      signature:0000089c
      device from 2021 and up?
      download:0000089c
      OKAY.
      signature
      OKAY.
 - Extracting sparse chunk partitionimage_0.000
 - Uploading sparse chunk D:\mobiletools\Root\SONY\XQ-BC72_61.0.A.23.20_Customized_TW\partition\partitionimage_0.000
      download:00006000
      OKAY.
      Repartition:0
      OKAY.
 - End of partition-image-LUN0_124936192_X-FLASH-ALL-4BA8.sin

Processing partition-image-LUN0_249896960_X-FLASH-ALL-4BA8.sin
 - Extracting from partition-image-LUN0_249896960_X-FLASH-ALL-4BA8.sin
 - Extracting signature partitionimage_0.cms
 - Uploading signature D:\mobiletools\Root\SONY\XQ-BC72_61.0.A.23.20_Customized_TW\partition\partitionimage_0.cms
      download:0000089c
      OKAY.
      signature
      OKAY.
 - Extracting sparse chunk partitionimage_0.000
 - Uploading sparse chunk D:\mobiletools\Root\SONY\XQ-BC72_61.0.A.23.20_Customized_TW\partition\partitionimage_0.000
      download:00006000
      OKAY.
      Repartition:0
      OKAY.
 - End of partition-image-LUN0_249896960_X-FLASH-ALL-4BA8.sin

Processing partition-image-LUN0_499818496_X-FLASH-ALL-4BA8.sin
 - Extracting from partition-image-LUN0_499818496_X-FLASH-ALL-4BA8.sin
 - Extracting signature partitionimage_0.cms
 - Uploading signature D:\mobiletools\Root\SONY\XQ-BC72_61.0.A.23.20_Customized_TW\partition\partitionimage_0.cms
      download:0000089c
      OKAY.
      signature
      OKAY.
 - Extracting sparse chunk partitionimage_0.000
 - Uploading sparse chunk D:\mobiletools\Root\SONY\XQ-BC72_61.0.A.23.20_Customized_TW\partition\partitionimage_0.000
      download:00006000
      OKAY.
      Repartition:0
      Error, didn't got Repartition OKAY reply! Got reply: FAILFAILRepartition

=========== FIRMWARES HISTORY LOG =============
NEW_VERSION: erased_user_data:true, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA1.0_R_25, cdf_version:Unknown: Jun 11 2021/04:24:12, fs_version:Unknown: Jun 11 2021/04:24:12, sw_version:61.0.A.5.106
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA1.0_R_27, cdf_version:Unknown: Jul  8 2021/03:49:52, fs_version:Unknown: Jul  8 2021/03:49:52, sw_version:61.0.A.11.23
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA1.0_R_27, cdf_version:Unknown: Aug 12 2021/15:49:45, fs_version:Unknown: Aug 12 2021/15:49:45, sw_version:61.0.A.11.92
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA1.0_R_31, cdf_version:Unknown: Sep 23 2021/21:59:32, fs_version:Unknown: Sep 23 2021/21:59:32, sw_version:61.0.A.14.14
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA1.0_R_31, cdf_version:Unknown: Sep 28 2021/19:26:19, fs_version:Unknown: Sep 28 2021/19:26:19, sw_version:61.0.A.15.35
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA1.0_R_31, cdf_version:Unknown: Nov 12 2021/09:59:35, fs_version:Unknown: Nov 12 2021/09:59:35, sw_version:61.0.A.23.20
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_104, cdf_version:Unknown: Jan 28 2022/20:12:28, fs_version:Unknown: Jan 28 2022/20:12:28, sw_version:61.1.A.2.211
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_104, cdf_version:Unknown: Mar 14 2022/21:18:13, fs_version:Unknown: Mar 14 2022/21:18:13, sw_version:61.1.A.6.2
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_104, cdf_version:Unknown: Mar 23 2022/17:47:07, fs_version:Unknown: Mar 23 2022/17:47:07, sw_version:61.1.A.7.35
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_104, cdf_version:Unknown: Apr 28 2022/23:45:38, fs_version:Unknown: Apr 28 2022/23:45:38, sw_version:61.1.A.9.73
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_105, cdf_version:Unknown: May 20 2022/23:49:43, fs_version:Unknown: May 20 2022/23:49:43, sw_version:61.1.A.9.128
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_105, cdf_version:Unknown: Jul 13 2022/22:21:38, fs_version:Unknown: Jul 13 2022/22:21:38, sw_version:61.1.A.9.219
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_105, cdf_version:Unknown: Aug  4 2022/23:46:56, fs_version:Unknown: Aug  4 2022/23:46:56, sw_version:61.1.A.11.36
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0_S_105, cdf_version:Unknown: Sep 30 2022/17:46:06, fs_version:Unknown: Sep 30 2022/17:46:06, sw_version:61.1.A.11.88
NEW_VERSION: erased_user_data:false, variant:user, s1boot_version:1322-1669_X_Boot_SM8350_LA2.0.1_T_205, cdf_version:Unknown, fs_version:Unknown, sw_version:61.2.A.0.382

=================================================

Set slot 'a' active.

Device is put now out of flash mode.
Sent command: continue.

Done.
Closing device.

**Comment by munjeni** [comment]
**partition_delivery.xml not exist in partition folder or no partition folder.**

You must NOT have partition files inside root folder! Put partition files into partition folder and also you must have partition_delivery.xml too inside partition folder! I can sugest, always download firmware trought XperiFirm, it will create all the files in the right folders

**Comment by weijen6** [comment]
I downloaded firmware version version 61.2.A.0.382 trought XperiFirm .
 partition_delivery.xml and boot_delivery.xml both in the root folder.
 Then I put them in the boot and partition folders respectively.
 Flashing completed, but unable to boot
 
![image](https://user-images.githubusercontent.com/32688959/212459324-b0ebf8d4-5882-42a4-ad0c-481c51f40dbb.png)

> **partition_delivery.xml not exist in partition folder or no partition folder.**
> 
> You must NOT have partition files inside root folder! Put partition files into partition folder and also you must have partition_delivery.xml too inside partition folder! I can sugest, always download firmware trought XperiFirm, it will create all the files in the right folders

**Comment by munjeni** [comment]
Please read here about rollback protection https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/
