### ISSUE TITLE
Support for Xperia 1

### ISSUE THREAD

**Issue by noelex** [munjeni/newflasher#6]
Looks like the size of root key hash of Xperia 1 is no longer 0x20. I made a slight change to ensure root key hash can be read successfully. Not sure whether this repository is still active so I post the patch and binary file here in case someone else needs this.

[newflasher.patch.zip](https://github.com/munjeni/newflasher/files/3270661/newflasher.patch.zip)

Notice:
Before flashing, please check partition directory in the firmware and ensure there is only 1 sin file for LUN0.  If your firmware is downloaded via XperiFirm, there should be two in the directory: partition-image-LUN0_62480384_X-FLASH-ALL-A2CD for 64GB flash and partition-image-LUN0_124960768_X-FLASH-ALL-A2CD for 128GB flash.  Keep one according to your phone's flash size and delete the other one.

**Comment by munjeni** [comment]
Hi, thanks! It can be better done by implementing by rest of the device info xml file, can you post it?

**Comment by noelex** [comment]
> Hi, thanks! It can be better done by implementing by rest of the device info xml file, can you post it?

Where can I get that?

**Comment by munjeni** [comment]
When unpack firmware with xperifirm its I think inside boot folder e.g. boot_delivery.xml or similar xml file, just look for xml file which contain line e.g. LUN0_62480384_X-FLASH-ALL-A2CD and post that file so I can look

**Comment by noelex** [comment]
Do you mean `partition_delivery.xml` inside `partition` directory? I got this from J9110's firmware:

```
<PARTITION_DELIVERY FORMAT="1">
  <PARTITION_IMAGES>
    <FILE PATH="partition-image-LUN0_124960768_X-FLASH-ALL-A2CD.sin"/>
    <FILE PATH="partition-image-LUN0_62480384_X-FLASH-ALL-A2CD.sin"/>
    <FILE PATH="partition-image-LUN1_4096_X-FLASH-ALL-A2CD.sin"/>
    <FILE PATH="partition-image-LUN2_4096_X-FLASH-ALL-A2CD.sin"/>
  </PARTITION_IMAGES>
</PARTITION_DELIVERY>

**Comment by noelex** [comment]
Can't find anything indicating which partition table to use. We probably need to read UFS info from the device and choose partition table base on its flash size.

**Comment by munjeni** [comment]
Hm, probably there is some new "getvar" variable which need to be implemented to newflasher. I'm downloading right now X1 firmware, will try to investigate. Can you tell me, with patch you provided everything is right?

**Comment by munjeni** [comment]
Can you try this? Need to know if I partition_delivery.xml parser is done right https://github.com/munjeni/newflasher/commit/15693f4a80ac012f55da0a813e18c10913caae65

Disabled partition flashing right now (in case partition_delivery.xml file exist in partition folder) so its safe right now for testing.

**Comment by munjeni** [comment]
This is list of commands I found in lilo bootloader

  sub_11E10("version", sub_11F74);
  sub_11E10("max-download-size", sub_11FC8);
  sub_11E10("Version-sony", sub_12024);
  sub_11E10("Loader-version", sub_12078);
  sub_11E10("serialno", sub_120D8);
  sub_11E10("version-bootloader", sub_120EC);
  sub_11E10("version-baseband", sub_12100);
  sub_11E10("product", sub_12114);
  sub_11E10("Phone-id", sub_12128);
  sub_11E10("Rooting-status", sub_12130);
  sub_11E10("Has-been-unlocked", sub_12138);
  sub_11E10("Device-id", sub_121F4);
  sub_11E10("Platform-id", sub_12260);
  sub_11E10("Frp-partition", sub_122CC);
  sub_11E10("secure", sub_122F0);
  sub_11E10("Sector-size", sub_122F8);
  sub_11E10("Ufs-info", sub_123C0);
  sub_11E10("Keystore-counter", sub_123C8);
  sub_11E10("Keystore-xcs", sub_12464);
  sub_11E10("Sake-root", sub_12518);
  sub_11E10("Default-security", sub_125A4);
  sub_11E10("S1-root", sub_125F0);
  sub_11E10("Security-state", sub_1263C);
  sub_11E10("USB-version", sub_12760);
  sub_11E10("Battery", sub_12768);
  sub_11E10("slot-count", sub_12770);
  sub_11E10("current-slot", sub_1288C);
  sub_11E10("slot-successful:a", sub_12928);
  sub_11E10("slot-successful:b", sub_129E0);
  sub_11E10("slot-unbootable:a", sub_12A98);
  sub_11E10("slot-unbootable:b", sub_12B50);
  sub_11E10("slot-retry-count:a", sub_12C08);
  sub_11E10("slot-retry-count:b", sub_12CA8);
  sub_11E10("Stored-security-state", sub_12D48);
  sub_11E10("Rollback-index-count", sub_12DB0);
  sub_11E10("X-conf", sub_12E1C);
  sub_11E10("Soc-unique-id", sub_12F0C);
  sub_11E10("SD-card-inserted", sub_12FE0);

Didn't found anything special related to ufs size. Have no idea right now how can we determine LUN0 size. Idea? It can be done by snifing whole usb packets using Device Monitorin Studio software in same time while flashing phone with Sony PC Companio software, that way I have done newflasher. Without device I'm unable to figure out things right now, need help from somebody who have device allready.

**Comment by noelex** [comment]
>  Can you tell me, with patch you provided everything is right? No flashing problem?

I can confirm that the patch works for J9110 and J8110, except a user in the [forum](https://forum.xda-developers.com/showpost.php?p=79710467&postcount=9) reported a problem:

> Works great but causes bootloop if you want to keep user data.

> And what you getting about ufs info in newflasher log?

newflasher just reported a part number of the chip: `SAMSUNG,KLUDG4U1EA-B0C1,0500`

I found that it should be viable to use `Get-gpt-info` command to retrieve partition image from the device, and calculate the flash size base on the GPT header. I can't flash my phone again since I've already done setting up and I don't have a spare one by hand. But I'll look into that to see if I can provide you more details.

**Comment by noelex** [comment]
I tried using `Get-ufs-info` command to retrieve UFS descriptor from the device.
`Get-ufs-info`  command will cause the device to return a binary response, containing descriptors of the UFS chip. In case of J9110 with KLUDG4U1EA-B0C1, I get:
```
40 00 00 00 00 00 03 04 01 00 01 7F 00 01 04 00
02 10 02 19 00 01 02 03 01 CE 10 10 02 00 1D 01
01 20 00 00 20 00 00 00 00 00 04 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
23 02 00 01 00 00 00 00 00 00 0C 00 00 00 00 01
DC B0 00 00 00 00 01 03 00 00 00 00 01 DC B0 00
00 00 00 23 02 01 01 01 01 00 00 03 00 0C 00 00
00 00 00 00 04 00 00 00 00 01 03 00 00 00 00 00
00 04 00 00 00 00 23 02 02 01 02 01 00 00 03 00
0C 00 00 00 00 00 00 04 00 00 00 00 01 03 00 00
00 00 00 00 04 00 00 00 00
```
The response above consists of a 64 byte Device Descriptor and three 35 byte Logical Unit Descriptors corresponding to LUN0, LUN1 and LUN2.

Data starting from `23 02 00` is the descriptor for LUN0, and at offset `0x0B` is a 64-bit big-endian integer representing total logical block count of this unit, in my case it's 0x1DCB000 (31240192). Together with the logical block size returned by `getvar:Sector-size` which is 4096 bytes, I can tell the size of the flash is 127959826432 bytes = 124960768 KB.

Logical block size is also described in the descriptor, but I'm not sure how is it interpreted. For more information, please refer the [specification](https://www.jedec.org/sites/default/files/docs/JESD220.pdf).

This should be much more reliable than the solution I mentioned in my previous comment. Hope this helps.

**Comment by munjeni** [comment]
Thanks, thats enought, great find! And here is implementation https://github.com/munjeni/newflasher/commit/7bc23e528c799769fb25f531b81c189f82dcc127 , hope working :)

**Comment by munjeni** [comment]
Done. Thanks for contribution!
