### ISSUE TITLE
Flashing custom ROMs (or TWRP)

### ISSUE THREAD

**Issue by VarLad** [munjeni/newflasher#61]
Thanks a lot for this project.
Any idea if this project can be extended to flash custom ROMs?
If not, can it flash something like TWRP? Normally using fastboot doesn't work for me.

**Comment by munjeni** [comment]
Hi, thanks, this can't be extended for custom roms even not for twrp, only Sony signed roms, it use Sony flashing protocol so only Sony signed roms can be flashed
