### ISSUE TITLE
Allow custom PID and VID

### ISSUE THREAD

**Issue by ImLoadingUuU** [munjeni/newflasher#63]
I have no usb device with vid:XXXX pid:XXXXX
is possible to add custom vid,pid args like
./newflasher <PID> <VID>
because i find out  every device has different pid,vid.  like mine
```

    USB 3.1 Bus:

      Host Controller Driver: AppleT8103USBXHCI

        XQ-BT52:

          Product ID: 0x320d
          Vendor ID: 0x0fce  (Sony Ericsson Mobile Communications AB)
          Version: 4.19
          Serial Number: HQ615841A8
          Speed: Up to 480 Mb/s
          Manufacturer: Sony
          Location ID: 0x01100000 / 1
          Current Available (mA): 500
          Current Required (mA): 0
          Extra Operating Current (mA): 0

    USB 3.1 Bus:

```
but in line 2725,2726 of newflasher.c
it use PID:0xb000b, VID: 0x0fce
so i hope newflasher could add a feature that can allow user use custom PID,VID.

( I dont have any C Experience, i tried to read the code and these are what i found)

**Comment by munjeni** [comment]
No, you have using wrong boot mode, you have using fastboot mode instead of bootloader mode! Bootloader mode is PID:B00B excatly the same as defined in newflasher, BOOB is on all xperia devices from xperia xz premium to the latest one.
