### ISSUE TITLE
Can't compile into an exe using mingw

### ISSUE THREAD

**Issue by HenriHawk42** [munjeni/newflasher#64]
Hey there,
I am using Windows and mingw, however I cannot for the life of me get newflasher to compile. I keep getting issues with make. Does this need to be compiled on a Linux machine? Or am I missing something?

If possible, it would be nice if there were prebuilt binaries for newflasher.

**Comment by munjeni** [comment]
I'm building on Linux trought i686-w64-mingw32-gcc package, don't care-know-havefreetime for anything else, hope this help

**Comment by munjeni** [comment]
prebuilt binaries is here -> https://forum.xda-developers.com/t/tool-newflasher-xperia-command-line-flasher.3619426/
