### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by kenfallon** [munjeni/newflasher#7]
Running make newflasher.x64 on Fedora release 29 gives the error 

```
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make: *** [makefile:24: newflasher.x64] Error 1
```
I couldn't find a lot on the Internet about this error and I'm not sure what additional information would help.
[report.txt](https://github.com/munjeni/newflasher/files/3293931/report.txt)

**Comment by munjeni** [comment]
This makefile is hardcoded, you will need to pass linker flags, e.g. https://github.com/munjeni/newflasher/commit/19e558f8a82d3966289b9c50670d2746d77add1f

**Comment by munjeni** [comment]
If this not help try remove -static flag from makefile.
