### ISSUE TITLE
Bootloop after flash Xperia 1 II (PDX203)

### ISSUE THREAD

**Issue by Candlemass** [munjeni/newflasher#70]
As the title reads. Bootloop continues before the "xperia" logo appears. Reflashing a custom rom to get out of the bootloop is possible but then the device has no imei number and therefore unable to read sim card for calls/network data.

**Comment by munjeni** [comment]
HI, this is all unrelated to newflsaher! Further questions please ask on xda forum in your device model subforum thank you
