### ISSUE TITLE
Support Mac arm

### ISSUE THREAD

**Issue by flzyup** [munjeni/newflasher#73]
Hi, Can you add mac arm-based CPU support? When I successfully compiled the project and using under arm-based Mac, it always shows timeout like the following:
![CleanShot 2024-08-01 at 08 14 18@2x](https://github.com/user-attachments/assets/b91f7ff8-c0b9-4dfe-836c-5de2478bcb89)

**Comment by munjeni** [comment]
Hi, mac reguire libusb1.0 version otherwise it not working, even if you compile with libusb1.0 and it not work I not going to support mac! Hope you get a way to ge it work.

**Comment by flzyup** [comment]
Thanks, I have libusb1.0 with compiled success, but failed to work at mac arm platform
